# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='message',
  serialized_pb='\n\rmessage.proto\x12\x07message\"\xc9\x02\n\tBugReport\x12 \n\x18phone_system_sdk_version\x18\x01 \x02(\x05\x12\x13\n\x0bphone_model\x18\x02 \x01(\t\x12\x15\n\rphone_product\x18\x03 \x01(\t\x12\x18\n\x10\x61pp_package_name\x18\x04 \x02(\t\x12\x18\n\x10\x61pp_version_code\x18\x05 \x02(\x05\x12\x0f\n\x07user_id\x18\x06 \x02(\t\x12&\n\x03tag\x18\x07 \x03(\x0b\x32\x19.message.BugReport.BugTag\x1aT\n\x06\x42ugTag\x12\r\n\x05\x63ount\x18\x01 \x02(\x05\x12.\n\x04type\x18\x02 \x02(\x0e\x32\x1a.message.BugReport.BugType:\x04JAVA\x12\x0b\n\x03tag\x18\x03 \x02(\t\"+\n\x07\x42ugType\x12\x08\n\x04JAVA\x10\x00\x12\n\n\x06NATIVE\x10\x01\x12\n\n\x06KERNEL\x10\x02\x42\x1e\n\x11\x63om.qasdk.messageB\tQaMessage')



_BUGREPORT_BUGTYPE = _descriptor.EnumDescriptor(
  name='BugType',
  full_name='message.BugReport.BugType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JAVA', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NATIVE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='KERNEL', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=313,
  serialized_end=356,
)


_BUGREPORT_BUGTAG = _descriptor.Descriptor(
  name='BugTag',
  full_name='message.BugReport.BugTag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='message.BugReport.BugTag.count', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='message.BugReport.BugTag.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='message.BugReport.BugTag.tag', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=227,
  serialized_end=311,
)

_BUGREPORT = _descriptor.Descriptor(
  name='BugReport',
  full_name='message.BugReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone_system_sdk_version', full_name='message.BugReport.phone_system_sdk_version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone_model', full_name='message.BugReport.phone_model', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone_product', full_name='message.BugReport.phone_product', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_package_name', full_name='message.BugReport.app_package_name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_version_code', full_name='message.BugReport.app_version_code', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='message.BugReport.user_id', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='message.BugReport.tag', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BUGREPORT_BUGTAG, ],
  enum_types=[
    _BUGREPORT_BUGTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=356,
)

_BUGREPORT_BUGTAG.fields_by_name['type'].enum_type = _BUGREPORT_BUGTYPE
_BUGREPORT_BUGTAG.containing_type = _BUGREPORT;
_BUGREPORT.fields_by_name['tag'].message_type = _BUGREPORT_BUGTAG
_BUGREPORT_BUGTYPE.containing_type = _BUGREPORT;
DESCRIPTOR.message_types_by_name['BugReport'] = _BUGREPORT

class BugReport(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class BugTag(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _BUGREPORT_BUGTAG

    # @@protoc_insertion_point(class_scope:message.BugReport.BugTag)
  DESCRIPTOR = _BUGREPORT

  # @@protoc_insertion_point(class_scope:message.BugReport)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\021com.qasdk.messageB\tQaMessage')
# @@protoc_insertion_point(module_scope)
