# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usermessage.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='usermessage.proto',
  package='',
  serialized_pb='\n\x11usermessage.proto\"k\n\nUserReport\x12 \n\x18phone_system_sdk_version\x18\x01 \x02(\x05\x12\x13\n\x0bphone_model\x18\x02 \x01(\t\x12\x15\n\rphone_product\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x02(\t\"\x1c\n\x06\x41nswer\x12\x12\n\nhas_update\x18\x01 \x02(\x08\x42&\n\x17\x63om.qasdk.message.modelB\x0bUserMessage')




_USERREPORT = _descriptor.Descriptor(
  name='UserReport',
  full_name='UserReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone_system_sdk_version', full_name='UserReport.phone_system_sdk_version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone_model', full_name='UserReport.phone_model', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone_product', full_name='UserReport.phone_product', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='UserReport.user_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=128,
)


_ANSWER = _descriptor.Descriptor(
  name='Answer',
  full_name='Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_update', full_name='Answer.has_update', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=130,
  serialized_end=158,
)

DESCRIPTOR.message_types_by_name['UserReport'] = _USERREPORT
DESCRIPTOR.message_types_by_name['Answer'] = _ANSWER

class UserReport(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _USERREPORT

  # @@protoc_insertion_point(class_scope:UserReport)

class Answer(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ANSWER

  # @@protoc_insertion_point(class_scope:Answer)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\027com.qasdk.message.modelB\013UserMessage')
# @@protoc_insertion_point(module_scope)
